apiVersion: v1
kind: Service
metadata:
  name: devops-app-metrics
  namespace: dev
  labels:
    app: devops-app
spec:
  selector:
    app: devops-app
  ports:
    - name: metrics
      port: 5000
      targetPort: 5000
  type: ClusterIP